package com.epam.gym.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import lombok.experimental.SuperBuilder;

// TODO:
//  For the first 3 points below please check all entities in the project, not just User
//  1. @Data produces @ToString with all fields included which leads to password being printed which is not secure
//  Consider using @Getter and @Setter instead (you can find what was generated by lombok at /target/classes once you've compiled the code)
//  2. @Data produces @EqualsAndHashCode with all fields included which can lead to issues with JPA entities:
//  bad with mutable fields + can trigger lazy loads + can break Sets/Maps when fields change
//  3. Primary key is usually named just 'id' to avoid confusion when other entity can have a foreign key i.e. 'userId'
//  4. According to the task, Trainer and Trainee should have @OneToOne relationship with User.
//   @Inheritance may become problematic:
//   - if one user can be both a trainer and a trainee
//   - it produces unneeded JOIN's every time you query for a Trainer or Trainee
//   - mapping and migration can be more complex than a simple unidirectional @OneToOne relationship
@Data
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "users")
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn(name = "user_type", discriminatorType = DiscriminatorType.STRING)
public abstract class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long userId;

    @NotBlank(message = "First name is required")
    @Column(name = "first_name", nullable = false)
    private String firstName;

    @NotBlank(message = "Last name is required")
    @Column(name = "last_name", nullable = false)
    private String lastName;

    @NotBlank(message = "Username is required")
    @Column(name = "username", nullable = false, unique = true)
    private String userName;

    @NotBlank(message = "Password is required")
    @Column(name = "password", nullable = false)
    private String password;

    @NotNull(message = "IsActive status is required")
    @Column(name = "is_active", nullable = false)
    @Builder.Default
    private Boolean isActive = true;
}