version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: gymdb_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev123
    ports:
      - "5432:5432"
    networks:
      - gym-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7.0
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: workloaddb_dev
    ports:
      - "27017:27017"
    networks:
      - gym-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  activemq:
    image: apache/activemq-classic:5.18.3
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - gym-network

  gym-crm:
    build: ./gym-crm-service
    container_name: gym-crm-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: dev123
      ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
      JWT_SECRET: mySecretKeyForJWTTokenGenerationWhichShouldBeLongEnough123456789
    depends_on:
      postgres:
        condition: service_healthy
      activemq:
        condition: service_started
    networks:
      - gym-network
    restart: on-failure

  trainer-workload:
    build: ./trainer-workload-service
    container_name: workload-app
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MONGO_HOST: mongodb
      MONGO_USER: admin
      MONGO_PASS: admin123
      ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
      JWT_SECRET: mySecretKeyForJWTTokenGenerationWhichShouldBeLongEnough123456789
    depends_on:
      mongodb:
        condition: service_healthy
      activemq:
        condition: service_started
    networks:
      - gym-network
    restart: on-failure

volumes:
  postgres-data:
  mongo-data:

networks:
  gym-network:
    driver: bridge