# Database Configuration
jdbc.driver=org.postgresql.Driver
jdbc.url=jdbc:postgresql://localhost:5432/gymdb
jdbc.username=postgres
jdbc.password=@Designer1980

# Hibernate Configuration
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=create-drop
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.use_sql_comments=true


hibernate.query.sqm.mutation_strategy=org.hibernate.query.sqm.mutation.internal.inline.InlineMutationStrategy
hibernate.query.sqm.insert_strategy=org.hibernate.query.sqm.mutation.internal.inline.InlineInsertStrategy