spring:
  config:
    activate:
      on-profile: stg

  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/workloaddb_stg?authSource=admin
      auto-index-creation: true

logging:
  level:
    root: WARN
    com.epam.gym.trainerworkloadservice: INFO
    org.springframework.jms: WARN
    org.apache.activemq: WARN