spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:27017/workloaddb_dev?authSource=admin
      auto-index-creation: true

logging:
  level:
    root: INFO
    com.epam.gym.trainerworkloadservice: DEBUG
    org.springframework.jms: INFO
    org.apache.activemq: INFO