name: Java CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - eureka-server
          - gym-crm-service
          - trainer-workload-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: mvn -B clean verify